interface ImportMetaEnv {
    readonly PLATFORM_PROVIDER_API_BASE_URL: string;
    readonly PLATFORM_PROVIDER_DELAYS_ENDPOINT_PATH: string;
    readonly PLATFORM_PROVIDER_INCIDENTS_ENDPOINT_PATH: string;
    readonly PLATFORM_PROVIDER_NOTIFICATIONS_ENDPOINT_PATH: string;
    readonly PLATFORM_PROVIDER_NOTIFICATION_SETTINGS_ENDPOINT_PATH: string;

    readonly PLATFORM_PROVIDER_VEHICLE_API_BASE_URL: string;
    readonly PLATFORM_PROVIDER_PLATFORM_PROVIDER_VEHICLES_ENDPOINT_PATH: string;

    readonly PLATFORM_PROVIDER_ROUTE_PLANNING_API_BASE_URL: string;
    readonly PLATFORM_PROVIDER_ROUTE_PLANNING_ROUTES_ENDPOINT_PATH: string;

    readonly PLATFORM_PROVIDER_BILLING_BASE_PATH: string;
    readonly PLATFORM_PROVIDER_BILLING_PLANS_ENDPOINT_PATH: string;
    readonly PLATFORM_PROVIDER_BILLING_SUBSCRIPTIONS_ENDPOINT_PATH: string;

    readonly PLATFORM_PROVIDER_PROFILES_API_BASE_URL: string;
    readonly PLATFORM_PROVIDER_PROFILES_STUDENTS_ENDPOINT_PATH: string;
    readonly PLATFORM_PROVIDER_PROFILES_PROFILES_ENDPOINT_PATH: string;

    readonly PLATFORM_PROVIDER_RELATIONSHIPS_API_BASE_URL: string;
    readonly PLATFORM_PROVIDER_RELATIONSHIPS_TUTOR_STUDENTS_RELATIONSHIPS_ENDPOINT_PATH: string;
    readonly PLATFORM_PROVIDER_RELATIONSHIPS_DATA_DELETION_REQUESTS_ENDPOINT_PATH: string;
}

interface ImportMeta {
    readonly env: ImportMetaEnv;
}